baseURL = 'https://geosim3d.com'
languageCode = 'en-us'
pagination.page = 6

[caches]
  [caches.images]
    dir = ':cacheDir/images'

[security]
  enableInlineShortcodes = true

  # Main Menu
  [[menu.Main]]
  name = "Gallery"
  url= "#gallery"
  weight = 1
  [[menu.Main]]
  name = "Service"
  url= "#service"
  weight = 1
  [[menu.Main]]
  name = "About"
  url= "/about/"
  weight = 3
  #[[menu.Main]]
  #name = "Blog"
  #url= "#blog"
  #weight = 4
  [[menu.Main]]
  name = "Products"
  url= "#pricing"
  weight = 5
  #[[menu.Main]]
  #name = "FAQ"
  #url= "#faq"
  #weight = 6
  [[menu.Main]]
  name = "Contact"
  url= "/contact/"
  weight = 7

  # Sitemap Menu
  [[menu.sitemap]]
  name = "Privacy Policy"
  url = "/privacy/"
  weight = 1
  [[menu.sitemap]]
  name = "Terms"
  url = "/terms/"
  weight = 2

[params]
  # theme_overrides = "css/overrides.css"
  aboutPageURL = "blog"
  contactLink = "contact"
  copyright = "© {year} <a href=\"https://staticmania.com/\" target=\"_blank\">StaticMania </a>"
  fabFormURL =  "https://fabform.io/v/5AIkk3aZ0g5S"
  googleAnalytics = "G-JZ95FEWF9K"
  logo = "images/geosim_logo.png"
  footerlogo = "images/geosim_logo.png"
  footerDescription = "All Rights Reserved ©2025"

  [params.address]
  address = "Denver, Colorado"
  email = "info@geosim.com"
  openingDesc = ""
  openingHours = ""
  phone = ""

  [params.map]
  APIkey = "AIzaSyC9rV6yesIygoVKTD6QLf_iCa9eiIIHqZ0"
  latitude = "45.4502528"
  longitude = "-122.783407"
  pinImage = "images/pin.png"

  # Social icons
  [[params.social]]
  icon = "ti-facebook"
  url = "https://www.facebook.com/"
  weight = 1
  [[params.social]]
  icon = "ti-twitter-alt"
  url = "https://twitter.com/"
  weight = 2
  [[params.social]]
  icon = "ti-dribbble"
  url = "https://dribbble.com/"
  weight = 3
  [[params.social]]
  icon = "ti-instagram"
  url = "https://www.instagram.com/"
  weight = 4
  
  
